### ISSUE TITLE
No symbol named in scope for ALL library functions/variables unless `library()` loaded in current console session

### ISSUE THREAD

**Issue by jordantgh** [posit-dev/positron#4072] opened 2024-07-18 16:32 UTC
## Positron Version:

2024.07.0 (system setup) build 2024.07.0-41

## Steps to reproduce the issue:

1. Create any `.r` file
2. Import any dependency with `library(xxxx)`
3. Use any variable/function defined in `xxxx`
4. Observe that it will be flagged as a `No symbol named in scope` error and will not provide proper hover tooltips
5. This warning goes away after sending `library(xxxx)` to the console, and comes back when upon restarting the console.

## What did you expect to happen?

I expected the language server would check the contents of imported libraries independently of the active console session, so that I wouldn't need to manually run code before it is linted correctly.

## Were there any error messages in the Output panel or Developer Tools console?

`no symbol named in scope` errors appear in the `Problems` tab, but no errors in `Output`

**Comment by DavisVaughan** [comment] 2024-07-18 17:08
Duplicate of https://github.com/posit-dev/positron/issues/2649

**Closed by DavisVaughan** 2024-07-18 17:08 UTC
Labels: bug
