### ISSUE TITLE
Antivirus false positive detection for Positron (Bitdefender) due to unsigned process / file

### ISSUE THREAD

**Issue by rempsyc** [posit-dev/positron#5350] opened 2024-11-13 15:13 UTC
#### Positron and OS details:

Positron Version: 2024.11.0 (user setup) build 140
Code - OSS Version: 1.93.0
Commit: e0d844b031f95acbf89f234a2cce2af9b6721f6c
Date: 2024-10-31T14:22:13.808Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

#### Interpreter details:

R 4.4.1

## Describe the issue:

Bitdefender fasely detected Positron as a critical threat / attack and quarantined 71 associated files.

## Steps to reproduce the issue:

1. This is a new installation from today and I tweaked a couple things like adding extensions and changing keyboard shortcuts.
2. I used the ctrl+shift+b shortcut (Rstudio) to install the current package (`datawizard`).
3. Installation started then was interrupted by Bitdefender.
4. This doesn't happen in RStudio.

## Expected or desired behavior:

No false flag by antivirus.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Positron was terminated by Bitdefender. Log file attached.
[vscode-app-1731510659006.log](https://github.com/user-attachments/files/17734692/vscode-app-1731510659006.log)

## Supporting screenshots

![Image](https://github.com/user-attachments/assets/38c1f025-5dd8-4ff9-aaf3-ef3333862a23)

![Image](https://github.com/user-attachments/assets/1db2be8e-4351-42f6-af5f-002856d83951)

![Image](https://github.com/user-attachments/assets/66b1485d-fab5-41e1-9063-3fdeb1bb7b40)

![Image](https://github.com/user-attachments/assets/88e12e54-2cae-44e1-8d71-a4f483f85d56)

![Image](https://github.com/user-attachments/assets/be1a30dd-922e-4781-b9fc-0acffc1ffa8b)

**Comment by juliasilge** [comment] 2024-11-13 19:37
Does your antivirus software have any other info about why Positron was identified as malicious? That would be really helpful. We do know that as a new application there will be some of this cropping up as the security vendors have not seen Positron before.

**Comment by rempsyc** [comment] 2024-11-13 19:39
The screenshot suggests it is because of an unsigned process / file. Do you mean more info than that?

**Comment by rempsyc** [comment] 2024-11-13 21:35
Strangely, there exists logs for when I manually ran a scan, but not for the Positron defense incident... I don't know how to extract more information. There doesn't seem to be a way to easily export logs of the event or anything like that :/ I just get something like this:

![Image](https://github.com/user-attachments/assets/e0528662-048a-402d-aacd-a90730c238b5)

And this

![Image](https://github.com/user-attachments/assets/4f7e77f7-2407-4359-9eb1-85777d5cbe9f)

There exists an area that lists all the files that were problematic, but it's unfortunately not possible to export or copy-paste, so I can only do screenshots (let me know if you want the whole long list)

![Image](https://github.com/user-attachments/assets/acf5ff4f-a5cf-4ee6-9807-8bae450f31d1)

**Comment by juliasilge** [comment] 2024-11-14 20:59
Without logs, it is quite difficult for us to know what might be happening unfortunately. 😔 

I will share that we believe we are signing/packaging Positron in an appropriate way and suspect the problem is that it is new. Products like this do typically have the ability to add certain applications to an allowlist, so one option would be for you to go to your IT folks and ask them to add Positron to that (assuming you don't manage this antivirus software yourself).

**Comment by rempsyc** [comment] 2024-11-14 22:08
Ok so I reported the false positive to Positron. Additionally, the agent's commented:
> Unfortunately, I do not know where you can find those logs, But I can ask my senior colleagues to look into this and then they will reach back to you via email with more information about that.

Fingers crossed!

**Comment by jonvanausdeln** [comment] 2024-11-25 18:32
@rempsyc , since we believe we've done all the right things in packaging and signing Positron I am going to close this issue for now.  If you get additional actionable information that could help us with your issue, please feel free to add it and re-open.

**Closed by jonvanausdeln** 2024-11-25 18:32 UTC
Labels: info needed

**Comment by rempsyc** [comment] 2024-12-02 00:52
Update from Bitdefender on November 26th, 2024, 20:02 EET:
> The false positive will be fixed through a signatures update by November 26th, 2024, 20:00 EET.

Suggesting it might already have been fixed.
