### ISSUE TITLE
R session `.libPaths()` restricted

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [posit-dev/positron#4346] opened 2024-08-14 07:33 UTC
#### Positron and OS details:

Positron Version: 2024.08.0 (user setup) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T13:58:54.164Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621

#### Interpreter details:

<pre>
> sessionInfo()
R version 4.4.1 Patched (2024-07-08 r86899 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.1 tools_4.4.1
</pre>

## Describe the issue:

1. Apparently, only the `library` subdirectory of `$R_HOME` is included in `.libPaths()`. (Note: this does not apply to R-devel - tested with 4.5 pre-release 2024-08-11 r86993 ucrt).
2. `.libPaths()` cannot be overridden in the R session.

### Failure to include `site-library` at startup

1. Make sure that there is a `site-library` in `$R_HOME`
2. Inpect `.libPaths()` in non-Positron R session
3. Start an R session in Positron
4. Inspect `.libPaths()` and compare

### Failure to override `.libPaths()`

1. Start an R session on Windows
2. `.libPaths(new = c(.libPaths(), tempfile("Rlib-")))`
3. Inspect `.libPaths()`

## Expected or desired behavior:

- Preferred: `.libPaths()` should be consistent across all R UIs
- Also OK: Restrictions to `.libPaths()` should be documented and exposed to configuration.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by jennybc** [comment] 2024-08-14 15:06
Can you show us the output from `.libPaths()` in the two scenarios? Just to make the difference even more concrete.

Also, will you confirm that what we're talking about libpath issues in the sense of this section of the R for Windows FAQ:

https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Does-R-run-under-Windows-7_002f8_002f10_002f11_002fServer-2012_002f2016_002f2022_003f

Are we talking about this?

> For a site installation, you can create a site-wide library directory anywhere convenient, and add it to the default package search path for all users via R_LIBS_SITE in etc\Renviron.site. See [What are HOME and working directories?](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What-are-HOME-and-working-directories_003f). There is a standard location for a site library, the site-library directory in the top-level R folder (which you would need to create with full control for the R installation account). This will be used for installation in preference to the main library folder if it exists.

**Comment by HenningLorenzen-ext-bayer** [comment] 2024-08-14 16:05
> Can you show us the output from `.libPaths()` in the two scenarios? Just to make the difference even more concrete.
> 
> Also, will you confirm that what we're talking about libpath issues in the sense of this section of the R for Windows FAQ:
> 
> https://cran.r-project.org/bin/windows/base/rw-FAQ.html#Does-R-run-under-Windows-7_002f8_002f10_002f11_002fServer-2012_002f2016_002f2022_003f
> 
> Are we talking about this?
> 
> > For a site installation, you can create a site-wide library directory anywhere convenient, and add it to the default package search path for all users via R_LIBS_SITE in etc\Renviron.site. See [What are HOME and working directories?](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What-are-HOME-and-working-directories_003f). There is a standard location for a site library, the site-library directory in the top-level R folder (which you would need to create with full control for the R installation account). This will be used for installation in preference to the main library folder if it exists.

### R 4.4.1

#### Positron

<pre>
> .libPaths()
[1] "C:/Users/XXX/AppData/Local/Programs/R/R-4.4.1patched/library"
</pre>

<pre>
> Sys.getenv() |> names() |> grep(pattern = "^R_", value = TRUE) |> Sys.getenv()
                                                                                                       R_ARCH 
                                                                                                       "/x64" 
                                                                                                R_COMPILED_BY 
                                                                                                 "gcc 13.2.0" 
                                                                                                       R_HOME 
                                                     "C:/Users/XXX/AppData/Local/Programs/R/R-4.4.1patched" 
                                                                                                  R_LIBS_SITE 
                                        "C:/Users/XXX/AppData/Local/Programs/R/R-4.4.1patched/site-library" 
                                                                                                  R_LIBS_USER 
                                                                                      "~/R/win-library/4.4.1" 
                                                                                              R_RTOOLS44_PATH 
"C:\\Users\\XXX\\R\\rtools\\44/x86_64-w64-mingw32.static.posix/bin;C:\\Users\\XXX\\R\\rtools\\44/usr/bin" 
                                                                                                       R_USER 
                                                          "C:\\Users\\XXX\\XXX\\Personal Data" 
</pre>

#### R Console

<pre>
> .libPaths()
[1] "C:/Users/ENAJA/R/R-4.4.1patched/site-library"
[2] "C:/Users/ENAJA/R/R-4.4.1patched/library" 
</pre>

**Comment by jennybc** [comment] 2024-08-19 22:40
Re: `site-library` not being present in `.libPaths()`: I haven't been able to reproduce that. I created `site-library` inside the folder that `R_HOME` reports and in both Positron and the terminal, I now see this:

```
> .libPaths()
[1] "D:/Users/jenny/AppData/Local/R/win-library/4.4"
[2] "C:/Program Files/R/R-4.4.1/site-library"
[3] "C:/Program Files/R/R-4.4.1/library"
```

I.e. the `site-library` folder appears in the "library tree", in the same position, in both contexts.

Can you say more about your R installation process? Am I right in assuming that you don't have admin privileges and you've elected to install R in a non-default location? Is there anything interesting you've done with `.Rprofile` (user or site level) or env vars or PATH, etc.?

Just to be safe: did `site-library` definitely pre-exist in the session where you say it's missing from `.libPaths()`? If you create it after an R session is launched, it won't come into effect until R restarts.

---

I also can't replicate the issue with modifying `.libPaths()`.

There are two really important points here (quoting from the docs for `.libPaths()`):

> If called with argument `new`, by default, the library search path is set to the **existing** directories in `unique(c(new, .Library.site, .Library))` and this is returned.
> ...
> How paths in new with a trailing slash are treated is OS-dependent.... On Windows filepaths with a trailing slash (or backslash) are invalid and existing directories specified with a trailing slash may not be added to the library search path.

So the code you provide above won't change `.libPaths()` because the new temporary directory doesn't actually exist yet. You'll need to create it and then add it to the library tree.

```
> .libPaths()
[1] "D:/Users/jenny/AppData/Local/R/win-library/4.4" "C:/Program Files/R/R-4.4.1/site-library"       
[3] "C:/Program Files/R/R-4.4.1/library"            

> .libPaths(new = c(.libPaths(), tempfile("Rlib-")))
> .libPaths()
[1] "D:/Users/jenny/AppData/Local/R/win-library/4.4"
[2] "C:/Program Files/R/R-4.4.1/site-library"       
[3] "C:/Program Files/R/R-4.4.1/library" 
           
> templib <- tempfile("Rlib-")
> templib
[1] "D:\\Users\\jenny\\AppData\\Local\\Temp\\1\\RtmpOEruJA\\Rlib-15c093a49f"
> dir.exists(templib)
[1] FALSE
> .libPaths(new = c(.libPaths(), templib))
> .libPaths()
[1] "D:/Users/jenny/AppData/Local/R/win-library/4.4"
[2] "C:/Program Files/R/R-4.4.1/site-library"       
[3] "C:/Program Files/R/R-4.4.1/library"  
          
> dir.create(templib)
> dir.exists(templib)
[1] TRUE
> .libPaths(new = c(.libPaths(), templib))
> .libPaths()
[1] "D:/Users/jenny/AppData/Local/R/win-library/4.4"                
[2] "C:/Program Files/R/R-4.4.1/site-library"                       
[3] "C:/Program Files/R/R-4.4.1/library"                            
[4] "D:/Users/jenny/AppData/Local/Temp/1/RtmpOEruJA/Rlib-15c093a49f"
```

**Comment by HenningLorenzen-ext-bayer** [comment] 2024-08-20 09:44
I think there one more weird thing required to reproduce this behavior :man_facepalming:

- Usually I install R in `C:\Users\XXX\R`, e.g. `C:\Users\XXX\R\R-4.4.1patched`
- Sometimes I install updated versions (R-patched, R_devel) into `C:\Users\XXX\AppData\Local\Programs\R`  by accident and some old versions were lingering around there.

Seems like Positron gets lead astray in this situation.

**Comment by jennybc** [comment] 2024-08-20 15:28
> Sometimes I install updated versions (R-patched, R_devel) into C:\Users\XXX\AppData\Local\Programs\R by accident and some old versions were lingering around there.

So I think you're saying that Positron _was_ finding an R installation but it was a different one from the one you were using as the non-Positron comparison? And that explains the differences.

I'm going to close this because I think we've figured things out. Please speak up if I'm wrong.

**Closed by jennybc** 2024-08-20 15:28 UTC
Labels: info needed
