### ISSUE TITLE
Error: Cannot shut down kernel; it is not (yet) running. (state = uninitialized)

### ISSUE THREAD

**Issue by apcamargo** [posit-dev/positron#4778] opened 2024-09-21 02:40 UTC
#### Positron and OS details:

```
Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z (4 days ago)
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 24.0.0
```

```
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

#### Interpreter details:

- R (4.4.1)
- Python (3.12.2)

## Describe the issue:

I am unable to change the kernel of a newly created Jupyter notebook to the R kernel because the uninitialized Python kernel cannot be shut down. It appears that Python is selected by default.

1. Work on a remote server (I haven't tried to replicate this on my local machine).
2. Install R 4.4.1 using [`rig`](https://github.com/r-lib/rig). The Python interpreter is the default installation, and no kernel or other libraries were installed.
3. Create a Jupyter notebook by creating a file with the `.ipynb` extension.
4. Open the notebook. An error message appears because no Python kernel is installed:
   <img width="410" alt="image" src="https://github.com/user-attachments/assets/059b1d23-6b8d-4136-9cc9-405022fe127d">
5. Click "Cancel".
6. Click on the kernel selection button and select R 4.4.1.
7. The following error message appears, and the R kernel does not start:
   <img width="461" alt="image" src="https://github.com/user-attachments/assets/29b79b95-688b-4604-a69a-a61076d63d35">

The only way I managed to change the kernel of that notebook is by manually editing the `language` field in the `.ipynb` file in text mode (see below) and then restart the "Positron Notebook Controllers" extension.

```json
{
 "cells": [],
 "metadata": {
  "language_info": {
   "name": "r"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

## Expected or Desired Behavior:

Ideally, Positron would detect that `ipykernel` or any kernel associated with the interpreter is not installed and would not attempt to initiate the notebook with it. I'm not sure how the default kernel is chosen, as I've never used the Python interpreter in Positron.

If Positron does attempt to initiate the notebook despite no kernel being available, I should be able to change to a different kernel without issue.

**Comment by petetronic** [comment] 2024-09-22 15:55
Hi @apcamargo and thanks for reporting this. I believe this may be issue https://github.com/posit-dev/positron/issues/4224.

**Comment by petetronic** [comment] 2024-09-22 16:02
Note: I set up an Ubuntu docker container with ssh to reproduce this scenario and I do see the same error that you reported after first canceling the ipykernel installation offered to a Python runtime, and then being unable to select an R kernel.

**Comment by petetronic** [comment] 2024-09-23 21:57
Closing as a duplicate of issue 4224 but please let us know if you think otherwise.

**Closed by petetronic** 2024-09-23 21:57 UTC
Labels: area: notebooks, area: runtimes, support

**Comment by apcamargo** [comment] 2024-09-23 22:57
Sounds good to me! That issue didn't show up in my search, but it seems to report the same problem
