### ISSUE TITLE
Shinylive-r in Quarto not renering

### ISSUE THREAD

**Issue by kv9898** [posit-dev/positron#4844] opened 2024-09-30 05:16 UTC
## System details:

Windows 11 64-bit

#### Positron and OS details:

Positron Version: 2024.09.0 (system setup) build 77
Code - OSS Version: 1.93.0
Commit: 9b6f7c066546a4c7f104368fc769fb3768b08bfd
Date: 2024-09-23T02:44:07.418Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Quarto: 1.6.15
shinylive (R package): 0.2.0
#### Interpreter details:

R 4.4.1

## Describe the issue:

Maybe related to #4676. Seems to be a *Windows only* issue. I can confirm that this *is a Positron or VS Code/Quarto VS Code extension problem* as my RStudio runs normally, in line with the previous issue but different from @jennybc's results. I will try to provide more information than my predecessor. Please let me know if there is more info needed.

In a nutshell:

- Positron/VS Code + Quarto + Shinylive + R = ×
- Positron/VS Code + Quarto + Shinylive + Python = √
- RStudio + Quarto + Shinylive + R = √

## Steps to reproduce the issue:

1. Start a new folder for the Quarto project
2. Open the folder in Positron
3. Execute `quarto add quarto-ext/shinylive` in Terminal to install the Quarto extension.
4. Run `install.packages("shinylive")` if it has not been installed before.
5. Start a .qmd file
6. Include the following minimum quarto document, and render:

````qmd
---
title: "Shinylive R test"
filters:
  - shinylive
---
```{shinylive-r}
#| standalone: true

```
````
7. You get an error.

## Expected or desired behavior:

Running normally as in RStudio.
![image](https://github.com/user-attachments/assets/c528598e-96d6-4c59-b161-980ce5991ba3)

From RStudio Background Jobs:
```
==> quarto preview shinyliver.qmd --to default --no-watch-inputs --no-browse

pandoc 
  to: html
  output-file: shinyliver.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Shinylive R test
  
ℹ Loading metadata database
✔ Loading metadata database ... done

Output created: shinyliver.html

Watching files for changes
Browse at http://localhost:5239/
```

## Were there any error messages in the UI, Output panel, or Developer Tools console?

From Terminal:
```
PS D:\OneDrive - London School of Economics\Desktop\shinyliveRError> quarto preview "d:/OneDrive - London School of Economics/Desktop/shinyliveRError/shinyliver.qmd" --no-browser --no-watch-inputs
pandoc 
  to: html
  output-file: shinyliver.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Shinylive R test

(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
 Error:
 PandocError {}
Error running filter D:/quarto/share/filters/main.lua:
...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:40: Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?

stack traceback:
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:40: in global 'throw_quarto_error'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:86: in global 'callRShinylive'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:113: in global 'callShinylive'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:286: in global 'ensureBaseSetup'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:315: in global 'ensureLanguageSetup'
        ...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:424: in function <...iveRError\_extensions\quarto-ext\shinylive\shinylive.lua:408>        
        [C]: in ?
        [C]: in method 'walk'
        D:/quarto/share/filters/main.lua:558: in local 'checked_walk'
        D:/quarto/share/filters/main.lua:610: in function 'run_emulated_filter'
        D:/quarto/share/filters/main.lua:1335: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        D:/quarto/share/filters/main.lua:1351: in upvalue 'run_emulated_filter_chain'
        D:/quarto/share/filters/main.lua:1389: in function <D:/quarto/share/filters/main.lua:1386>
stack traceback:
        D:/quarto/share/filters/main.lua:558: in local 'checked_walk'
        D:/quarto/share/filters/main.lua:610: in function 'run_emulated_filter'
        D:/quarto/share/filters/main.lua:1335: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        D:/quarto/share/filters/main.lua:1351: in upvalue 'run_emulated_filter_chain'
        D:/quarto/share/filters/main.lua:1389: in function <D:/quarto/share/filters/main.lua:1386>
  ```
  
It seems that there was no error from the Developer Tools console 
![image](https://github.com/user-attachments/assets/291a73c0-5026-4a26-9175-bb2233dfc092)

**Comment by timtmok** [comment] 2024-09-30 14:44
Duplicate of #4676 based on the stack trackback and the repro steps. Thank you for logging the issue and especially for opening it in Quarto.

**Closed** 2024-09-30 14:44 UTC
