### ISSUE TITLE
Confusion around toggling vs. focusing a viewpane, such as the Panel

### ISSUE THREAD

**Issue by EmilHvitfeldt** [posit-dev/positron#3284] opened 2024-05-28 18:22 UTC
## Positron Version:

Positron Version: 2024.05.0 (Universal) build 1307
Code - OSS Version: 1.89.0
Commit: a32eab640724ad6257adc4f7636986afe7c73467
Date: 2024-05-27T03:48:23.965Z
Electron: 28.2.8
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

## Steps to reproduce the issue:

1. click `side-by-side layout` in `customize layout` menu
2. click `toggle panel` button 

(to repeat, you sometimes have to press a different layout preset THEN select side-by-side again)

https://github.com/posit-dev/positron/assets/14034784/b216d114-c7fb-485d-a287-455ab27c81fc

## What did you expect to happen?

I would expect that pressing the `toggle panel` button would remove the panel on the first click, instead of on the second click

## Were there any error messages in the output or Developer Tools console?

Nope

**Comment by petetronic** [comment] 2024-07-10 20:27
Closing this as a duplicate of #811 that we re-opened to reconsider this issue.

**Closed by petetronic** 2024-07-10 20:27 UTC
Labels: enhancement, area: ui
