### ISSUE TITLE
Allow option not to snap back to browser() in R debugger

### ISSUE THREAD

**Issue by timdisher** [posit-dev/positron#4736] opened 2024-09-18 20:11 UTC
I generally write scripts with large amounts of analyses conducted within functions. In RStudio I can place a browser call to enter the function environment and add to the function arguments/make and test edits easily before exiting the debugger and testing the new changes. In Positron running code in another script or further down the same function using Command + Enter snaps back to the browser location every time. 

Is it possible to disable this behaviour?

**Comment by petetronic** [comment] 2024-09-18 23:46
Thanks @timdisher for raising this enhancement. Tagging @lionel- for his thoughts?

**Comment by lionel-** [comment] 2024-09-19 06:58
We agree! Duplicate of #2786.

**Closed by lionel-** 2024-09-19 06:58 UTC
Labels: duplicate, enhancement, lang: r, support, area: debugger
