### ISSUE TITLE
Extension page wrongly displays buttons

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#4041] opened 2024-07-17 08:20 UTC
## Positron Version:
Positron Version: 2024.07.0 (system setup) build 2024.07.0-59
Code - OSS Version: 1.91.0
Commit: b189a8b9c77a1fcc8a79732bfe24b2fa018436cc
Date: 2024-07-17T03:23:20.020Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
## Steps to reproduce the issue:

Open the extension page in the newest version

## What did you expect to happen?
Installed extensions do not show "Install button"

## Were there any error messages in the Output panel or Developer Tools console?

![image](https://github.com/user-attachments/assets/e9444bcb-2e00-4e72-89fa-34c0eefacf8a)

**Comment by juliasilge** [comment] 2024-07-17 15:42
Thanks for this report! I am not able to reproduce this problem on Windows with the latest Positron prerelease. Do you have any other insight about when this started happening, what causes it to happen? Does it persist through closing and reopening the app? Are there are any errors in the Developer Tools console that look related?

**Closed** 2024-07-22 20:27 UTC
Labels: bug
