### ISSUE TITLE
Little bug in `.rs.api.viewer()`: "object 'normalizedPath' not found"

### ISSUE THREAD

**Issue by kv9898** [posit-dev/positron#4304] opened 2024-08-09 13:55 UTC
## System details:

Windows 11

#### Positron and OS details:

Positron Version: 2024.08.0 (system setup) build 5
Code - OSS Version: 1.91.0
Commit: Unknown
Date: 2024-08-06T16:06:18.274Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.2.2

## Describe the issue:

kableExtra table cannot be viewed at all. An error pops up. This differs from #3759 where the HTML is not in the right format.

![image](https://github.com/user-attachments/assets/eb8d543a-4f9f-4575-90a6-c004c9483e61)

## Steps to reproduce the issue:

1. Start any R file (r or quarto)
2. run `knitr::kable(mtcars) |> kableExtra::kable_minimal()`

## Expected or desired behavior:

The table can be viewed in the help panel.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Error in `x$sizingPolicy`:
! $ operator is invalid for atomic vectors
Hide Traceback
    ▆
 1. ├─base (local) `<fn>`(x)
 2. └─kableExtra:::print.kableExtra(x)
 3.   ├─base::print(html_kable)
 4.   └─print.shiny.tag.list(html_kable)
 5.     └─base::isTRUE(x$sizingPolicy$knitr$figure)

**Comment by juliasilge** [comment] 2024-08-09 17:53
I just tried this out on Windows and was not able to reproduce the error:

![Screenshot 2024-08-09 at 11 53 12 AM](https://github.com/user-attachments/assets/ce679f23-cd31-4e4d-9dbb-01ac349d002e)

Can you [check out some logs for us](https://github.com/posit-dev/positron/wiki/Troubleshooting#python-and-r-logs) to see if we can discover what may be the problem in your particular situation? We would be interesting in any errors related to this that you may see in:

- the "Console: R 4.2.2" output channel
- the "Developer Tools" console maybe?

**Comment by kv9898** [comment] 2024-08-09 18:22
Strange... It seems that it is because I loaded the R package "modelsummary" which I use for tables.
![image](https://github.com/user-attachments/assets/83fdf008-b3ce-4e74-b278-df0ad305c129)

![image](https://github.com/user-attachments/assets/0e7db209-8b3a-40a8-8aa0-736e04666a5d)

Here are screenshots of the R 4.2.2 console and the Developer Tools console.

I will update my R to 4.4.1 and see if this problem persists. However, I tried with RStudio and it worked properly.

**Comment by kv9898** [comment] 2024-08-09 18:48
Long story short: it seems that Positron is currently incompatible with _tinytable_ rather than with kableExtra.

I updated my R and both packages (modelsummary and kableExtra) and now the `knitr::kable(mtcars) |> kableExtra::kable_minimal()` commands work properly - the problem was probably that my versions were too old.

However, now the modelsummary commands do not work anymore:
Try `library(modelsummary` followed by `datasummary(mpg~Mean, mtcars)` - a new error pops up - perhaps because `modelsummary` 2.0.0 now uses `tinytable` as its default table-drawing backend.

The error:
![image](https://github.com/user-attachments/assets/907289ee-769d-47ea-9670-56e99a13c254)

From Developer Tools Console:
![image](https://github.com/user-attachments/assets/b9bd1599-a986-4383-9bf7-6866f8b6aee9)

After I asked modelsummary to switch back to 'options(modelsummary_factory_default = 'kableExtra')' , things work.
After switching back to tinytable using options(modelsummary_factory_default = 'tinytable'), the command `datasummary(mpg~Mean, mtcars)` doesn't work again!

**Comment by juliasilge** [comment] 2024-08-09 19:03
Ah, I think I found the bug here:

https://github.com/posit-dev/ark/blob/43ad620e0f75be4046a30fbd16082db344954d76/crates/ark/src/modules/rstudio/stubs.R#L48

There is no `normalizedPath` at that point.

Here is the reproducible example:

```r
library(modelsummary)
datasummary(mpg ~ Mean, mtcars)
```

@kv9898 Thank you so much for the report! I'm going to mark part of our convo as "off topic" to make it easier to see the real problem here.

**Comment by kv9898** [comment] 2024-08-09 19:23
Thank you so much for your timely replies! Your efficiency has always amazed me. Never expected real time responses.

**Comment by testlabauto** [comment] 2024-08-12 14:53
With build 2024.08.0-31:
I am still seeing:
<img width="399" alt="image" src="https://github.com/user-attachments/assets/a171da3b-6d94-4ca0-9c59-3ee5ad8f0149">
Seems like it should have made the build, but not sure.

**Comment by DavisVaughan** [comment] 2024-08-12 16:13
@testlabauto we've merged on the ark side but we haven't bumped the ark version and synced it on the positron side

**Comment by kv9898** [comment] 2024-08-15 16:49
Are we getting an update of ark/positron to fix this issue this/next week?

**Comment by juliasilge** [comment] 2024-08-19 14:44
Thanks for your patience on this @testlabauto! The fix is now incorporated in 2024.08.0 build 48.

**Comment by testlabauto** [comment] 2024-08-19 17:16
### Verified Fixed
    Positron Version(s) : 2024.08.0-48
    OS Version          : OSX

### Test scenario(s) 

library(modelsummary)
datasummary(mpg ~ Mean, mtcars)

Link(s) to TestRail test cases run or created:
N/A

**Closed by testlabauto** 2024-08-19 17:16 UTC
Labels: bug, lang: r, support
