### ISSUE TITLE
Keyboard shortcut weirdness with shortcut for R: Insert new section

### ISSUE THREAD

**Issue by rkrug** [posit-dev/positron#4766] opened 2024-09-20 09:17 UTC
## System details:
M1 Macbook Pro
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

R 4.4.1 or Python

## Describe the issue:

Keyboard shortcuts for shown after SHIFT-CMD-P are different to the ones defined int the json and noe of them work in an R file

## Steps to reproduce the issue:

SHIFT-CMD-P - look at R: Insert a new section, and press the gear icon and compare

![Screenshot 2024-09-20 at 11 10 59](https://github.com/user-attachments/assets/f71547e9-989d-445c-b9c4-6cba5ff0b202)
![Screenshot 2024-09-20 at 11 11 17](https://github.com/user-attachments/assets/0404dc65-b853-425a-87e6-5fb4a9b8db1a)

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

**Comment by petetronic** [comment] 2024-09-20 14:25
Hi @rkrug, thanks for raising this. I believe this is a bug with the RStudio Keymap Extension, which is showing shortcuts in menus even if it is not enabled. See https://github.com/posit-dev/positron/issues/3993

If you look at registered Keyboard Shortcuts (press Cmd+K then S) for this command, you'll see two entries for this command:
- R: Insert a new section = Cmd+K H (when: editorLangId == 'r')
- R: Insert a new section = Shift+Cmd+R (when: config.rstudio.keymap.enable && ... && editorLangId == 'r')

**Comment by petetronic** [comment] 2024-09-23 21:58
Closing as a duplicate of issue 3993 but please let us know if you think otherwise.

**Closed by petetronic** 2024-09-23 21:58 UTC
