### ISSUE TITLE
Readline/input requests do not work in notebooks

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#4920] opened 2024-10-07 09:39 UTC
In VS Code readline/input prompts are surfaced to the user as a quick pick selection:

https://github.com/user-attachments/assets/7ffa75cd-bce0-415f-9579-d512324fc684

In Positron the quick pick menu is not opened and the cell execution hangs until interrupted:

https://github.com/user-attachments/assets/ab1f2adc-1543-422c-8880-214298a68154

Note that even though it says `"but this frontend does not support input request"`, I think it's a misleading error message caused by interrupting the input request. We do send our `execute_request` with `allow_stdin: true`, and we do receive an `input_request`. See log:

<details>
[Positron] Sending code to Python: input("foo> ")
[Positron] SEND execute_request to Shell: {"buffers":[],"content":{"code":"input(\"foo> \")","allow_stdin":true,"silent":false,"store_history":true,"user_expressions":{},"stop_on_error":true},"header":{"msg_id":"positron-notebook-cell-15","msg_type":"execute_request","version":"5.0","date":"2024-10-07T09:12:46.138Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{},"parent_header":{}}
[Positron] SEND execute_request: OK
[Positron] Python kernel status changed: idle => busy
[Positron] RECV status/busy from iopub: {"header":{"msg_id":"7a582421-2ff79ea8f9e4da8334072419_79148_68","msg_type":"status","username":"lionel","session":"7a582421-2ff79ea8f9e4da8334072419","date":"2024-10-07T09:12:46.144859Z","version":"5.3"},"parent_header":{"msg_id":"positron-notebook-cell-15","msg_type":"execute_request","version":"5.0","date":"2024-10-07T09:12:46.138000Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{},"content":{"execution_state":"busy"},"buffers":[]}
[Positron] RECV execute_input from iopub: {"header":{"msg_id":"7a582421-2ff79ea8f9e4da8334072419_79148_69","msg_type":"execute_input","username":"lionel","session":"7a582421-2ff79ea8f9e4da8334072419","date":"2024-10-07T09:12:46.147798Z","version":"5.3"},"parent_header":{"msg_id":"positron-notebook-cell-15","msg_type":"execute_request","version":"5.0","date":"2024-10-07T09:12:46.138000Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{},"content":{"code":"input(\"foo> \")","execution_count":6},"buffers":[]}
[Positron] RECV input_request from stdin: {"header":{"msg_id":"7a582421-2ff79ea8f9e4da8334072419_79148_70","msg_type":"input_request","username":"lionel","session":"7a582421-2ff79ea8f9e4da8334072419","date":"2024-10-07T09:12:46.162542Z","version":"5.3"},"parent_header":{"msg_id":"positron-notebook-cell-15","msg_type":"execute_request","version":"5.0","date":"2024-10-07T09:12:46.138000Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{},"content":{"prompt":"foo> ","password":false},"buffers":[]}
[Positron] Interrupting Python
[Positron] SEND interrupt_request to Control: {"buffers":[],"content":{},"header":{"msg_id":"d45f3858-a289-4243-bba5-39b79532926a","msg_type":"interrupt_request","version":"5.0","date":"2024-10-07T09:12:49.860Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{},"parent_header":{}}
[Positron] SEND interrupt_request: OK
[Positron] RECV status/busy from iopub: {"header":{"msg_id":"7a582421-2ff79ea8f9e4da8334072419_79148_71","msg_type":"status","username":"lionel","session":"7a582421-2ff79ea8f9e4da8334072419","date":"2024-10-07T09:12:49.862435Z","version":"5.3"},"parent_header":{"msg_id":"d45f3858-a289-4243-bba5-39b79532926a","msg_type":"interrupt_request","version":"5.0","date":"2024-10-07T09:12:49.860000Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{},"content":{"execution_state":"busy"},"buffers":[]}
[Positron] RECV status/idle from iopub: {"header":{"msg_id":"7a582421-2ff79ea8f9e4da8334072419_79148_73","msg_type":"status","username":"lionel","session":"7a582421-2ff79ea8f9e4da8334072419","date":"2024-10-07T09:12:49.901347Z","version":"5.3"},"parent_header":{"msg_id":"d45f3858-a289-4243-bba5-39b79532926a","msg_type":"interrupt_request","version":"5.0","date":"2024-10-07T09:12:49.860000Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{},"content":{"execution_state":"idle"},"buffers":[]}
[Positron] RECV error from iopub: {"header":{"msg_id":"7a582421-2ff79ea8f9e4da8334072419_79148_74","msg_type":"error","username":"lionel","session":"7a582421-2ff79ea8f9e4da8334072419","date":"2024-10-07T09:12:49.901846Z","version":"5.3"},"parent_header":{"msg_id":"positron-notebook-cell-15","msg_type":"execute_request","version":"5.0","date":"2024-10-07T09:12:46.138000Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{},"content":{"traceback":["\u001b[0;31m---------------------------------------------------------------\u001b[0m","\u001b[0;31mKeyboardInterrupt\u001b[0m             Traceback (most recent call last)","Cell \u001b[0;32mIn[6], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;43minput\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mfoo> \u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n","File \u001b[0;32m/opt/homebrew/lib/python3.12/site-packages/ipykernel/kernelbase.py:1282\u001b[0m, in \u001b[0;36mKernel.raw_input\u001b[0;34m(self, prompt)\u001b[0m\n\u001b[1;32m   1280\u001b[0m     msg \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mraw_input was called, but this frontend does not support input requests.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1281\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m StdinNotImplementedError(msg)\n\u001b[0;32m-> 1282\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_input_request\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1283\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mprompt\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1284\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_parent_ident\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mshell\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43... (truncated)
[Positron] RECV execute_reply from shell: {"header":{"msg_id":"7a582421-2ff79ea8f9e4da8334072419_79148_75","msg_type":"execute_reply","username":"lionel","session":"7a582421-2ff79ea8f9e4da8334072419","date":"2024-10-07T09:12:49.904170Z","version":"5.3"},"parent_header":{"msg_id":"positron-notebook-cell-15","msg_type":"execute_request","version":"5.0","date":"2024-10-07T09:12:46.138000Z","session":"00c66971a994cbeaae9e5b50bc8ab970","username":"lionel"},"metadata":{"started":"2024-10-07T09:12:46.147727Z","dependencies_met":true,"engine":"a553d619-91f6-4acd-b68d-4f6668124a2f","status":"error"},"content":{"status":"error","traceback":["\u001b[0;31m---------------------------------------------------------------\u001b[0m","\u001b[0;31mKeyboardInterrupt\u001b[0m             Traceback (most recent call last)","Cell \u001b[0;32mIn[6], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;43minput\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mfoo> \u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n","File \u001b[0;32m/opt/homebrew/lib/python3.12/site-packages/ipykernel/kernelbase.py:1282\u001b[0m, in \u001b[0;36mKernel.raw_input\u001b[0;34m(self, prompt)\u001b[0m\n\u001b[1;32m   1280\u001b[0m     msg \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mraw_input was called, but this frontend does not support input requests.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1281\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m StdinNotImplementedError(msg)\n\u001b[0;32m-> 1282\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_input_request\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1283\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mprompt\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1284\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[... (truncated)
[Positron] Python kernel status changed: busy => idle
</details>

**Comment by seeM** [comment] 2024-10-08 13:46
Ah, it looks like this is a duplicate of https://github.com/posit-dev/positron/issues/4199.

**Closed by seeM** 2024-10-08 13:46 UTC
Labels: bug, area: notebooks
