### ISSUE TITLE
Fix layout of column summary

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#4062] opened 2024-07-18 01:11 UTC
## Steps to reproduce the issue:

1. Open data explorer on `qa-example-content/data-files/100x100/100x100.parquet`.

```
import pandas as pd
pandas100x100 = pd.read_parquet('/Users/brian/Work/qa-example-content/data-files/100x100/100x100.parquet')
```

2. Scroll the table summary panel downwards until you see that there are layout issues in this view.

<img width="1381" alt="image" src="https://github.com/user-attachments/assets/73ec7d33-0a05-4cd3-8701-e49ab25357b3">

## What did you expect to happen?

I expected a clean layout with truncated column names with ellipses.

## Were there any error messages in the Output panel or Developer Tools console?

No.

**Comment by petetronic** [comment] 2024-08-13 18:48
Closing as a duplicate of https://github.com/posit-dev/positron/issues/4301

**Closed by petetronic** 2024-08-13 18:48 UTC
Labels: bug, area: data explorer, frontend
