### ISSUE TITLE
Python autocomplete doesnt work on notebook

### ISSUE THREAD

**Issue by mertgoksel** [posit-dev/positron#4006] opened 2024-07-13 12:41 UTC
Type: <b>Bug</b>

get into a notebook

case 1:
type import 
no package can be found

case 2:
type "pri"
"print" is not shown in suggestions.

VS Code version: Positron 1.90.0 (9f24124be55ef409fb6b6c75ee80232f298cd56b, 2024-07-12T03:18:15.685Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)

**Comment by nstrayer** [comment] 2024-07-15 14:55
<img width="603" alt="image" src="https://github.com/user-attachments/assets/eca104df-654d-4c0c-acd4-a66a51844e7b">
<img width="643" alt="image" src="https://github.com/user-attachments/assets/769e4748-6371-4d67-9ec2-4022cb9a5cd4">
I can't reproduce on a mac. Can anyone on Windows reproduce?

**Comment by petetronic** [comment] 2024-07-15 21:09
I can't reproduce this issue in Positron on Windows with a basic Notebook using Python 3.11.6 as the kernel. 

It is possible the language runtime stopped somehow and thus a kernel and LSP are not available to the notebook? To see if you have a kernel, you could declare a variable and assign it a value. After executing the cell, if the variable shows up in the Variables pane for that notebook's runtime, at least the kernel is running.

Beyond that, we'd need to look at the relevant python runtime related channels for the notebook in the Output tab of the Panel to see if there are any hints as to what happened.

**Comment by RayleighKim** [comment] 2024-07-17 02:44
I think I reproduced..

![image](https://github.com/user-attachments/assets/6f1091ab-70d5-4d95-8cb0-69b30c5c17f2)

![image](https://github.com/user-attachments/assets/7fbfcf38-6f02-486a-a171-548de59c4b91)


Left is the jupyter noteook file which I created before using Positron
Right is the jupyter notebook file which I created using Positron.

As you see, both notebook using same python environment.

**Comment by RayleighKim** [comment] 2024-07-17 02:49
I think I successfully reproduced, even though I didn't want to.....

![image](https://github.com/user-attachments/assets/39575f6d-993e-4c05-97f4-1aa1494022c6)

I saved jupyter notebook on the right ( I mentioned above... that had not been not saved)

Now code suggestion is gone...

**Comment by PhilippFW** [comment] 2024-07-17 06:56
same here - autocomplee works in python .py file but not in jupyter notebook .ipynb

**Comment by juliasilge** [comment] 2024-07-17 21:54
Hmmmm, if you are experiencing this problem, could you go to "Output" and choose the channel for your notebook? It will look something like this:

![Screenshot 2024-07-17 at 3 51 05 PM](https://github.com/user-attachments/assets/e663a591-d626-4039-93cd-a70d2113ac3f)

Could you save that log and attach it as a file to a comment here? We're especially interested in what these notebook logs say about the LSP server. Mine, with working autocomplete, says near the beginning:

```
[Positron] Starting Positron LSP server on port 46057
[Positron] Starting LSP server positron-lsp-python-2-8f657d76 for 127.0.0.1:46057
[Positron] Creating 'positron.lsp' client for Python
[Positron] SEND comm_open to Shell: {"buffers":[],"content":{"target_name":"positron.lsp","comm_id":"positron-lsp-python-2-8f657d76","data":{"client_address":"127.0.0.1:46057"}},"header":{"msg_id":"72634796-6f97-403d-be0d-3ca5d4ae185a","msg_type":"comm_open","version":"5.0","date":"2024-07-17T21:46:39.365Z","session":"5dc885ad16f7276fa0abd509a20e03a6","username":"juliasilge"},"metadata":{},"parent_header":{}}
```

**Comment by RayleighKim** [comment] 2024-07-18 02:55
I truly want to use positron...


![image](https://github.com/user-attachments/assets/d8539ca8-f856-4ff8-bbbd-e5774f7a70ae)
[Output_Log.txt](https://github.com/user-attachments/files/16276988/Output_Log.txt)



![image](https://github.com/user-attachments/assets/7a75576b-5630-4df5-a576-f13950f0d8ae)
[Output_Log2.txt](https://github.com/user-attachments/files/16277022/Output_Log2.txt)

**Comment by seeM** [comment] 2024-07-18 11:10
Thanks for sharing the logs! I can't see anything suspicious from those. Could you please try updating the `python.languageServerLogLevel` setting to `debug` and sharing the logs if it fails again? Note that you will have to wait for it to happen again since the log level will only be set for future sessions.

**Comment by RayleighKim** [comment] 2024-07-22 02:09
> Thanks for sharing the logs! I can't see anything suspicious from those. Could you please try updating the `python.languageServerLogLevel` setting to `debug` and sharing the logs if it fails again? Note that you will have to wait for it to happen again since the log level will only be set for future sessions.

I'm sorry, Could you please show me how to do it?
I'm so new to this IDE that I don't know how to set.

If you could let me know how, then I would share the whole logs again.
Sadly to say, it's very easy for me to reproduce...

**Comment by RayleighKim** [comment] 2024-07-23 11:47
![image](https://github.com/user-attachments/assets/4cb01296-dbd8-428e-b25a-c37659a8433e)
[Output_Log4.txt](https://github.com/user-attachments/files/16348101/Output_Log4.txt)

I hope that any suspicious parts are found in this log.
If there's anything additional you would like me to try, please let me know. I will try and upload the log again.

**Comment by seeM** [comment] 2024-07-23 15:36
Thank you for sharing the log! I can't figure out how to reproduce the issue from the logs, but there are clues:

1. So far we've only seen this reported on Windows.
2. The LSP server successfully starts, accepts the connection from the editor, initializes, and receives a `workspace/didChangeConfiguration` message.
3. No `textDocument/didOpen` LSP messages are received. On my laptop, I see one `textDocument/didOpen` message for each cell in the notebook, and numerous `textDocument/didChange` as I type. This makes me think that the problem is on the client side.

Could you please also share the log file for the "Python" output channel? You can run the "Output: Show Output Channels..." command and then select "Python".

**Comment by RayleighKim** [comment] 2024-07-24 01:08
![image](https://github.com/user-attachments/assets/6fe1150a-fbe2-406b-90c7-d0aa15924b7f)
![image](https://github.com/user-attachments/assets/f6fcc63d-252f-4319-9c65-ef342a525b41)
![image](https://github.com/user-attachments/assets/0bf66e45-7705-4b7c-94b1-737ff1fdfba1)

[Log_Console.txt](https://github.com/user-attachments/files/16355819/Log_Console.txt)
[Log_Notebook.txt](https://github.com/user-attachments/files/16355820/Log_Notebook.txt)
[Log_Python.txt](https://github.com/user-attachments/files/16355821/Log_Python.txt)

Something different happened this time.
Positron asked me to install ipykernel, and I accepted. (it was my first time to see this.)
It was not helpful anyway.
All the screenshots and the logfiles in this comment are made after installing ipykernel.

**Comment by seeM** [comment] 2024-07-24 15:30
Thank you again @RayleighKim! I've created PR #4137 with a potential fix for this issue but have not yet been able to verify it on a Windows computer. We'll post follow-up messages here as the PR goes through verification.

**Comment by RayleighKim** [comment] 2024-07-24 16:06
Thank you.

To be honest, I'm not very familiar with GitHub(and opensource communication culture..), so I might have ignored many guidelines/rules of writing issue comment. Even so, thank you for guiding me on exactly what I need to do.
If there's anything else that needs to be checked or tested, please let me know.

**Comment by piyuranjan** [comment] 2024-07-26 19:55
I am noticing the same issue in Quarto markdown with R code in Windows. I searched and landed on this issue. I think this is being actively worked on but I am sharing screenshots in case they help. Let me know if sharing any logs would help.

Autocomplete in question is for a variable that exists in the current session environment. Console works but editor doesn't.
![image](https://github.com/user-attachments/assets/fcb08f54-b19a-45bc-a8c7-7545c4d1b9c6)
![image](https://github.com/user-attachments/assets/37a784ff-dad1-4264-80ff-560649fcac42)

**Comment by juliasilge** [comment] 2024-07-29 18:54
@piyuranjan That is a pretty different problem, I believe. Do you mind opening a new issue with your details? If you are able to recreate the problem with a pretty minimal Quarto file (i.e. short) and latest Positron build that would be super helpful.

**Comment by piyuranjan** [comment] 2024-07-30 14:59
@juliasilge, thank you for responding! You are correct that this is a different problem. I was able to get to the source when I was trying to create a minimal example. The issue is caused when a code block is inside a callout and they both end at adjacent lines (without an extra new line between them). This causes the autocomplete/intellisense in Positron to completely stop after it has happened in the markdown. I am unsure if this is a Positron or Quarto issue. Let me know if I should open a new issue with Positron. I couldn't find any mentions of this with Quarto as well.

**Comment by testlabauto** [comment] 2024-08-01 20:24
### Verified Fixed
    Positron Version(s) : ?
    OS Version          : Windows

### Test scenario(s) 

Marking as verified based on Pete's note on the PR.

Link(s) to TestRail test cases run or created: 
N/A

**Closed by testlabauto** 2024-08-01 20:24 UTC
Labels: bug, os-windows, area: notebooks, lang: python, support

**Comment by RayleighKim** [comment] 2024-08-02 01:34
Thank you all for fix.

I want to know which version that I can use.

**Comment by testlabauto** [comment] 2024-08-02 15:28
Hi @RayleighKim ,

Please try [2024.07.0-125](https://github.com/posit-dev/positron/releases/tag/2024.07.0-125)
We verified this issue with a dev build but it should be fixed in 125.

Please let me know if you still see issues.

Thank you for your report!
