### ISSUE TITLE
Strange results for plots created by *tinyplot*

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#4611] opened 2024-09-08 19:52 UTC
#### Positron and OS details:

Positron Version: 2024.09.0 (system setup) build 1
Code - OSS Version: 1.92.0
Commit: f37f4f5044a2a619e73d5db61a31e37fbd3faf18
Date: 2024-09-03T02:35:34.573Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.4.1

## Describe the issue:

When creating plots using the _tinyplot_ package, I get strange results. Either a corrupted plot image, which is cropped, a blank plot, or an error message:

```
Error in `plot.new()`:
! figure margins too large
Show Traceback
```

![image](https://github.com/user-attachments/assets/82fdc53b-050a-43d6-8140-9774edffebcf)

Results look good in RStudio.

## Steps to reproduce the issue:

Run following code:

```r
library(tinyplot)
aq = transform(
  airquality,
  Month = factor(Month, labels = month.abb[unique(Month)])
)
aq$grp <- sample.int(3, nrow(aq), replace = TRUE)

tinyplot(
  Temp ~ Day | Month + grp,
  data = aq,
  pch = 16,
  cex = 2,
  frame = FALSE,
  grid = TRUE,
  facet.args = list(bg = "grey90")
)

tinyplot(
  y = aq$Temp,
  x = aq$Day,
  by = interaction(aq$Month, aq$grp),
  data = aq,
  pch = 16,
  cex = 2,
  frame = FALSE,
  grid = TRUE
)

tinyplot(
  Temp ~ Day | Month,
  facet = ~ grp,
  data = aq,
  pch = 16,
  cex = 2,
  frame = FALSE,
  grid = TRUE,
  facet.args = list(bg = "grey90")
)
```

## Expected or desired behavior:

Results from RStudio

![image](https://github.com/user-attachments/assets/99138f28-1401-483c-9df2-057d9ed5cc30)

![image](https://github.com/user-attachments/assets/54ddadf4-d72e-4c50-a21f-c3827bf7cca2)

![image](https://github.com/user-attachments/assets/22ae2e29-aaa4-41ad-a418-b3dd365f7478)

**Comment by grantmcdermott** [comment] 2024-09-09 14:14
Duplicate of https://github.com/posit-dev/positron/issues/3667 if I'm not mistaken. 

The problem appears to stem from margin adjustments, e g. for positioning outer legends or facets, and is affecting other base R graphics.

**Comment by strengejacke** [comment] 2024-09-09 14:20
Ah, might be! Then this one can be closed.

**Closed** 2024-09-09 14:54 UTC
