### ISSUE TITLE
Ctrl + Enter in .qmd file does not run code line by line

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#3757] opened 2024-06-30 20:24 UTC
## Positron Version:
Positron Version: 2024.06.1 (system setup) build 2024.06.1-27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T01:33:58.809Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
## Steps to reproduce the issue:

1. Create a new `.qmd` file
2. Create a new Python cell

```py
import pandas as pd
import numpy as np

a = 1
b = 2
```
3. Place the cursor in the first line and press `Ctrl + Enter`

## What did you expect to happen?
The code run only the first line

## Were there any error messages in the output or Developer Tools console?
There was no error but the it run the whole code cell, not line by line

**Comment by juliasilge** [comment] 2024-06-30 21:18
This is a duplicate of #1646 if you would like to add any additional info there. Thanks!

**Closed by juliasilge** 2024-06-30 21:18 UTC
Labels: bug
