### ISSUE TITLE
ANSI code printed in the Terminal pane on windows powershell

### ISSUE THREAD

**Issue by cderv** [posit-dev/positron#4859] opened 2024-10-01 08:55 UTC
#### Positron and OS details:

````
Positron Version: 2024.09.0 (user setup) build 103
Code - OSS Version: 1.93.0
Commit: 8274fe26a1582fa0dd0096d6631b500f591416c4
Date: 2024-09-30T02:52:11.236Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
````

#### Terminal details:

Using Powershell 7.4.5 `pwsh` on Windows 10.0.22631.0

## Describe the issue:

![image](https://github.com/user-attachments/assets/228c46e6-04cb-4ad0-a308-d42095daca67)

When opening a new terminal in PowerShell I see this above. It seems the sequence `\x1b[0m` is an ANSI escape code used in terminal environments to reset the text formatting.

I am surprised to see it, while opening same terminal in VSCODE does not show it. 

Is this something on my side ? Or does Positron use this specific command and somehow it is shown in terminal pane ? 

I see it used several place across code - though I don't think this is working for powershell. 

````powershell
❯ Write-Host "\x1b[0m"
\x1b[0m
````

My understanding is that Powershell expect rather ``"`e[0m" ``

This is available from powershell 6 I think: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7.4#escape-e

For example 

![image](https://github.com/user-attachments/assets/a91e189f-ede0-4c29-ae99-2fbc435a1143)

So maybe this ANSI code needs to be adapted in powershell context ? 

## Steps to reproduce the issue:

1. Open Positron on Windows with powershell 7 available
2. Open a terminal windows with powershell

## Expected or desired behavior:

Terminal does not show `\x1b[0m` character

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Not relevant (I think)

**Comment by timtmok** [comment] 2024-10-02 16:32
I don't see this myself on two different Windows installs (both Powershell 7.4.5).
![Image](https://github.com/user-attachments/assets/6d550855-67cf-46b8-b401-18a911b6b1c1)
![Image](https://github.com/user-attachments/assets/b7ca359c-7149-496a-b392-008b30087d6d)

It seems like it was a problem upstream in a 1.90 Insiders release: https://github.com/microsoft/vscode/issues/211922

@cderv Are you using any customizations on top of Powershell like oh-my-posh?

**Comment by jennybc** [comment] 2024-10-02 16:37
I also cannot reproduce this on my Windows laptop.

**Comment by cderv** [comment] 2024-10-02 16:40
Interesting ! 

I do have customization - I should have deactivate. I will check this. 

Though, there is still a difference between VSCODE and Positron using same shell, and I thought it would be the same. 

I'll come back to you.

**Comment by cderv** [comment] 2024-10-02 20:33
So it seems to be link to using starship (https://starship.rs/) in Terminal inside Positron. 

Somehow the initialisation prints something that Terminal in Positron does show, while Windows Terminal or Terminal Pane in VSCODE does not show. 

I'd like to understand so I'll keep digging.

**Comment by timtmok** [comment] 2024-10-04 16:56
I tried apply the Gruvbox Rainbow preset and it appears to be similar as VS Code

Positron:
![Image](https://github.com/user-attachments/assets/c8992a65-d5a6-40a1-8eae-9acecfd93194)

VS Code:
![Image](https://github.com/user-attachments/assets/3d7617a6-e449-49a3-b948-316b24567664)

I'll leave open for now to see if there's anything else but I don't think there's much customization, if any, with Positron and the Terminal that would cause this.

**Comment by cderv** [comment] 2024-10-04 18:18
Thanks @timtmok. I did not found where this character is coming from. It only shows if init starship in my `$profile` - so probably linked to that. 

For sure, not a positron thing as-is, so I understand if you close to keep issue tracker cleaner. If I found why, I'll share here later.

**Comment by jonvanausdeln** [comment] 2024-10-07 14:45
Closing for now as it's not a Positron specific issue.. but feel free to re-open if it looks otherwise.

**Closed by jonvanausdeln** 2024-10-07 14:45 UTC
