### ISSUE TITLE
Console: Scrolling can get into a broken state after Console has been moved

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#2116] opened 2024-01-23 19:26 UTC
Thanks to @chendaniely for his usability testing session yesterday. We discovered that scrolling in the Console can get pretty broken after you move the Console from its original location:

https://github.com/posit-dev/positron/assets/12505835/b55d62c4-c6f8-4b7d-8c69-765eb595516e

It remains broken if you move it back to its original location:

https://github.com/posit-dev/positron/assets/12505835/5318f5dc-afd0-4777-a7b1-df4e952e8702

I don't have an exact reproducible set of steps for this and cannot currently reproduce the problem with the R console.

**Comment by petetronic** [comment] 2024-07-31 14:42
@cderv Also reported seeing a similar issue with double overlay rendering of console output on Windows in a Console that was in a maximized state of the Panel in its typical location in the center.

**Comment by petetronic** [comment] 2024-07-31 14:53
We've had a few more reports of this since, bringing back to Triage

**Comment by jennybc** [comment] 2024-07-31 15:58
I am one of those recent reports and I had definitely flipped through some of our preset layouts that move the Console. It may have been the first time I (temporarily) moved the Console from its default location and this maneuver definitely coincided with the first time I've seen this weird scrolling/overlay phenomenon.

**Comment by cderv** [comment] 2024-07-31 20:25
FWIW I am never moved the layout and moved the console. Though regarding moving stuff around, it saw this the same as I tried to install some extension, and move them from left sidebar to right panel. Nothing to do with the R console, but could be seen as "messing with layout" category maybe. 🤷‍♂️ 

After closing Positron and reopening, I can't reproduce yet. So I am not sure what caused the behavior

**Comment by juliasilge** [comment] 2024-08-26 18:51
Reported again in https://github.com/posit-dev/positron/discussions/4477

**Comment by jonvanausdeln** [comment] 2024-09-16 16:38
### Verified Fixed
Positron Version(s) : [2024.09.0-38](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-38)
OS Version(s) : Windows11, Ubuntu 22

### Test scenario(s) 


Followed repro steps in PR.. scroll works as expected now in Console.

### Link(s) to TestRail test cases run or created:

**Closed by jonvanausdeln** 2024-09-16 16:38 UTC
Labels: bug, area: console, support
