### ISSUE TITLE
ark returns rust output in jupyter but not positron

### ISSUE THREAD

**Issue by nhejazi** [posit-dev/positron#4382] opened 2024-08-17 01:33 UTC
I couldn't find an Ark issue that resolved this, and the behavior seems to be specific to its interaction with Jupyter/Zed but is hidden on the user side in Positron.

#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 5
Code - OSS Version: 1.91.0
Commit: Unknown
Date: 2024-08-06T17:08:14.498Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

R 4.4.0

## Describe the issue:

When trying the Ark Jupyter kernel in the Zed editor, I encountered an error where R code is sometimes successfully executed (e.g., and other times not, for printing `ggplot2` objects) and assumed it might be an editor incompatibility. Since the issue doesn't occur at all with Python code, using `ipykernel`, I tried the R code in Jupyter Lab and Positron, with the issue being replicated in Jupyter Lab but not happening in Positron.

## Steps to reproduce the issue:

1. Jupyter notebook for replicating in Jupyter Lab
2. R script for replicating in Zed and Positron

The script is an MWE intended for testing...
```r
# %%
library(data.table)
library(ggplot2)

# %%
data(mtcars)
head(mtcars)

# %%
p <- ggplot(mtcars, aes(x = mpg, y = disp)) +
  geom_point() +
  theme_bw() +
  labs(title = "Miles per gallon vs. Displacement",
	   x = "Miles per gallon",
	   y = "Displacement")
p

# %%
m <- glm(mpg ~ disp, data = mtcars)
summary(m)
```

## Expected or desired behavior:

Same output in Jupyter Lab and Zed as Ark produces in Positron, i.e., no warnings/messages from passing things back and forth via Rust.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Warning message from running the first two lines of the script above in Jupyter Lab and Zed

Input:
```
# %%
library(data.table)
library(ggplot2)
```

Output:
```
2024-08-17T01:13:51.841693Z  INFO  Received execution request JupyterMessage { zmq_identities: [[97, 55, 52, 99, 97, 57, 57, 48, 45, 48, 48, 53, 97, 45, 52, 98, 54, 52, 45, 57, 56, 102, 54, 45, 56, 99, 100, 48, 51, 54, 53, 101, 57, 97, 53, 102]], header: JupyterHeader { msg_id: "584f438f-432c-4a42-a875-8962708ea5e7", session: "a74ca990-005a-4b64-98f6-8cd0365e9a5f", username: "", date: "2024-08-17T01:13:51.834Z", msg_type: "execute_request", version: "5.2" }, parent_header: None, content: ExecuteRequest { code: "# %%\nlibrary(data.table)\nlibrary(ggplot2)", silent: false, store_history: true, user_expressions: Object {}, allow_stdin: true, stop_on_error: true } }
    at crates/amalthea/src/socket/shell.rs:227
```

This happens for every execution/cell, continuing on in the script:

Input:
```
# %%
data(mtcars)
head(mtcars)

# %%
p <- ggplot(mtcars, aes(x = mpg, y = disp)) +
  geom_point() +
  theme_bw() +
  labs(title = "Miles per gallon vs. Displacement",
	   x = "Miles per gallon",
	   y = "Displacement")
p
```

Output:
```
2024-08-17T01:14:03.625231Z  INFO  Received execution request JupyterMessage { zmq_identities: [[97, 55, 52, 99, 97, 57, 57, 48, 45, 48, 48, 53, 97, 45, 52, 98, 54, 52, 45, 57, 56, 102, 54, 45, 56, 99, 100, 48, 51, 54, 53, 101, 57, 97, 53, 102]], header: JupyterHeader { msg_id: "0dd40e4a-4e57-498c-8248-0509330ed4f8", session: "a74ca990-005a-4b64-98f6-8cd0365e9a5f", username: "", date: "2024-08-17T01:14:03.621Z", msg_type: "execute_request", version: "5.2" }, parent_header: None, content: ExecuteRequest { code: "# %%\ndata(mtcars)\nhead(mtcars)\n\n# %%\np <- ggplot(mtcars, aes(x = mpg, y = disp)) +\n  geom_point() +\n  theme_bw() +\n  labs(title = \"Miles per gallon vs. Displacement\",\n\t   x = \"Miles per gallon\",\n\t   y = \"Displacement\")\np", silent: false, store_history: true, user_expressions: Object {}, allow_stdin: true, stop_on_error: true } }
    at crates/amalthea/src/socket/shell.rs:227
```

**Comment by nhejazi** [comment] 2024-08-18 16:46
possibly related to https://github.com/posit-dev/positron/issues/2098

**Comment by lionel-** [comment] 2024-08-19 15:00
Indeed, this looks like a duplicate of #2098. We'll track your use case (usage within zed) as part of that issue, thanks for the report!

**Closed by lionel-** 2024-08-19 15:00 UTC

**Comment by nhejazi** [comment] 2024-08-19 17:04
thanks @lionel- --and just to clarify, this seems to only appear in Zed by way of Jupyter, i.e., it happens in the standard Jupyter Lab notebook interface too, so it's probably only due to Jupyter.
